# Generated by Django 3.2.8 on 2021-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.TextField()),
                ('Prestataire', models.TextField()),
                ('DateAssistance', models.TextField()),
                ('Statut', models.TextField()),
                ('RéférenceVeo', models.TextField()),
                ('Intervention', models.TextField()),
                ('Immatriculation', models.TextField()),
                ('Nomclient', models.TextField()),
                ('PhotosAvant', models.TextField()),
                ('PhotosAprès', models.TextField()),
                ('PhotosConstat', models.TextField()),
                ('PhotosHistorique', models.TextField()),
                ('DateAssistance_h', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bris_De_Glace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.TextField()),
                ('Référencedossier', models.TextField()),
                ('Immatriculation', models.TextField()),
                ('Datesinistre', models.TextField()),
                ('NomAssuré_souscripteur', models.TextField()),
                ('PhotosAvant', models.TextField()),
                ('PhotosAprès', models.TextField()),
                ('Statut', models.TextField()),
                ('Datedecréation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veodata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CaseNumber', models.TextField()),
                ('Type', models.TextField()),
                ('ContactName', models.TextField()),
                ('Immatriculation', models.TextField()),
                ('ImmatriculationAdverse', models.TextField()),
                ('Okpoursouscription', models.TextField()),
                ('Statutgarage', models.TextField()),
                ('Status', models.TextField()),
                ('CreatedDate', models.TextField()),
                ('Datesinistre', models.TextField()),
                ('Nomintermédiairecp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Veoservices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Dossier', models.TextField()),
                ('Statut', models.TextField()),
                ('Date_sinistre', models.TextField()),
                ('Garantie', models.TextField()),
                ('Procédure', models.TextField()),
                ('Expert', models.TextField()),
                ('Immatriculation', models.TextField()),
                ('Date_création', models.TextField()),
                ('Date_validité_début', models.TextField()),
                ('Date_validité_fin', models.TextField()),
                ('Date_validité_début_Adv', models.TextField()),
                ('Date_validité_fin_Adv', models.TextField()),
                ('RateFraude', models.FloatField()),
                ('Photos_Avant', models.TextField()),
                ('Photos_en_cours', models.TextField()),
                ('Photos_après_réparation', models.TextField()),
                ('ImmatriculationAdverse', models.TextField()),
                ('R1', models.TextField()),
                ('R2', models.TextField()),
                ('R3', models.TextField()),
                ('R4', models.TextField()),
                ('R5', models.TextField()),
                ('R6', models.TextField()),
                ('R7', models.TextField()),
                ('R8', models.TextField()),
                ('R9', models.TextField()),
                ('observation', models.TextField()),
                ('StatutDoute', models.TextField()),
            ],
        ),
    ]
